before_script:
  - ["bash", "set_commit_status.sh", "pending", "The pipeline is running"]

stages:
  - test

test:
  stage: test
  script:
    - sleep 30
  tags:
    - macos

update_status_success:
  when: on_success
  script:
    - ["bash", "set_commit_status.sh", "success", "The pipeline succeeded"]
