before_script:
  - echo "Building ${CI_COMMIT_SHA}..."

stages:
  - test

test:
  stage: test
  script:
    - sleep 30
  tags:
    - macos

update_status_success:
  when:
  script:
    - curl -X POST \
        https://api.github.com/repos/kchudy/gitlab-ci-test/statuses/${CI_COMMIT_SHA} \
        -d '{"state": "success", "target_url": "http://localhost/root/gitlab-ci-test/pipelines/'${CI_PIPELINE_ID}'", "description": "The build succeeded!", "context": "continuous-integration/gitlab"}' \
        -H "Authorization: token ${GITHUB_TOKEN}"
