before_script:
  - echo "Building ${CI_COMMIT_SHA}..."

stages:
  - test

test:
  stage: test
  script:
    - sleep 30
  tags:
    - macos

update_status_success:
  when: on_success
  script:
    - ./set_commit_status.sh
