before_script:
  - ./set_commit_status.sh pending Pending

stages:
  - test

test:
  stage: test
  script:
    - sleep 30
  tags:
    - macos

update_status_success:
  when: on_success
  script:
    - ./set_commit_status.sh success Success
